import React, {useEffect, useState} from 'react';
import axios from 'axios'
import { Hint } from 'react-autocomplete-hint';

import styles from './SearchBar.module.css';

function SearchBar() {
    const [hintData, setHintData] = useState([])
    const [text, setText] = useState('')
  
    const getData = async () => {
       const res = await axios.get('https://jsonplaceholder.typicode.com/users')
        var hintArray = [
            '1414 Degrees Ltd',
            '1ST Group Ltd',
            '3P Learning Ltd',
            '4DS Memory Ltd',
            '5G Networks Ltd',
            '88 Energy Ltd',
            '8COMMON Ltd',
            '8I Holdings Ltd',
            '8IP Emerging Companies Ltd',
            '8VIC Holdings Ltd',
            '9 Spokes International Ltd',
            'A-Cap Energy Ltd',
            'A2B Australia Ltd',
            'Abacus Property Group',
            'Abilene Oil and Gas Ltd',
            'Absolute Equity Performance Fund Ltd',
            'Abundant Produce Ltd',
            'Accent Resources NL',
            'Acorn Capital Investment Fund Ltd',
            'Acrow Formwork and Construction Services Ltd',
            'ACRUX Ltd',
            'Actinogen Medical Ltd',
            'Acumentis Group Ltd',
            'AD1 Holdings Ltd',
            'Adacel Technologies Ltd',
            'Adairs Ltd',
            'Adalta Ltd',
            'Adavale Resources Ltd',
            'Adelaide Brighton Ltd',
            'Adherium Ltd',
            'Admedus Ltd',
            'Admiralty Resources NL',
            'Adriatic Metals Plc',
            'Adslot Ltd',
            'Advanced Braking Technology Ltd',
            'ADX Energy Ltd',
            'Aeeris Ltd',
            'Aeris Environmental Ltd',
            'Af Legal Group Ltd',
            'Affinity Energy and Health Ltd',
            'African Energy Resources Ltd',
            'African Gold Ltd',
            'AFT Corporation Ltd',
            'Aft Pharmaceuticals Ltd',
            'AGL Energy Ltd',
            'Agricultural Land Trust',
            'Aguia Resources Ltd',
            'Ahalife Holdings Ltd',
            'Aic Mines Ltd',
            'Ainsworth Game Technology Ltd',
            'Alita Resources Ltd',
            'Allegiance Coal Ltd',
            'Alliance Resources Ltd',
            'Alligator Energy Ltd',
            'Alpha Hpa Ltd',
            'Alterra Ltd',
            'Althea Group Holdings Ltd',
            'Amaero International Ltd',
            'American Pacific Borates Ltd',
            'Andromeda Metals Ltd',
            'Anglo Australian Resources NL',
            'Anglogold Ashanti Ltd',
            'Anteotech Ltd',
            'Antipodes Global Shares (Quoted Managed Fund)',
            'Apiam Animal Health Ltd',
            'Apn Industria REIT',
            'Ardiden Ltd',
            'Argosy Minerals Ltd',
            'Ark Mines Ltd',
            'Aruma Resources Ltd',
            'Asaleo Care Ltd',
            'Asf Group Ltd',
            'Athena Resources Ltd',
            'Auckland International Airport Ltd',
            'Audalia Resources Ltd',
            'Audinate Group Ltd',
            'Aura Energy Ltd',
            'Aurora Absolute Return Fund',
            'Aurora Labs Ltd',
            'Auscann Group Holdings Ltd',
            'Austral Gold Ltd',
            'Australian Agricultural Company Ltd',
            'Australian Agricultural Projects Ltd',
            'Australian Bauxite Ltd',
            'Australian Dairy Nutritionals Group',
            'Australian Ethical Investment Ltd',
            'Australian Finance Group Ltd',
            'Australian Foundation Investment Company Ltd',
            'Australian Governance & Ethical INDEX Fund',
            'Auswide Bank Ltd',
            'Avenira Ltd',
            'Betashares Australia 200 ETF',
            'Betashares Australian Government Bond ETF',
            'Betashares Australian High Interest Cash ETF',
            'ETFs Battery Tech & Lithium ETF',
            'Force Commodities Ltd',
            'LIFE360 Inc',
            'Oneall International Ltd',
            'Pointerra Ltd',
            'The a2 Milk Company Ltd',
            'Tubi Ltd',
            'Aurora Global Income Trust',
            'Alternative Investment Trust',
            'Astivita Ltd',
            'Aeris Resources Ltd',
            'Activex Ltd',
            'Authorised Investment Fund Ltd',
            'Air New Zealand Ltd',
            'Acacia Coal Ltd',
            'Asian American Medical Group Ltd',
            'AJ Lucas Group Ltd',
            'Altura Mining Ltd',
            'Armour Energy Ltd',
            'Alexium International Group Ltd',
            'Asaplus Resources Ltd',
            'Academies Australasia Group Ltd',
            'Aspire Mining Ltd',
            'Auking Mining Ltd',
            'Audio Pixels Holdings Ltd',
            'AML3D Ltd',
            'Alderan Resources Ltd',
            'Alcidion Group Ltd',
            'Australian Leaders Fund Ltd',
            'Ardent Leisure Group Ltd',
            'Argo Global Listed Infrastructure Ltd',
            'Alkane Resources Ltd',
            'Aristocrat Leisure Ltd',
            'Als Ltd',
            'Analytica Ltd',
            'Altium Ltd',
            'Atlas Arteria',
            'Alchemy Resources Ltd',
            'AMA Group Ltd',
            'Ambition Group Ltd',
            'Amcor Plc',
            'Arrow Minerals Ltd',
            'Alto Metals Ltd',
            'Ausmex Mining Group Ltd',
            'Amcil Ltd',
            'Aurelia Metals Ltd',
            'Aeon Metals Ltd',
            'Agrimin Ltd',
            'Ambertech Ltd',
            'AMP Ltd',
            'Atomos Ltd',
            'Allegra Orthopaedics Ltd',
            'Aerometrex Ltd',
            'Ansila Energy NL',
            'Austin Engineering Ltd',
            'Amani Gold Ltd',
            'Ansell Ltd',
            'Advance Nanotek Ltd',
            'Antisense Therapeutics Ltd',
            'Anatara Lifesciences Ltd',
            'Austsino Resources Group Ltd',
            'Aus Tin Mining Ltd',
            'Australia and New Zealand Banking Group Ltd',
            'Assetowl Ltd',
            'Ausmon Resources Ltd',
            'Australian Unity Office Fund',
            'Apollo Minerals Ltd',
            'Apollo Consolidated Ltd',
            'Auroch Minerals Ltd',
            'American Patriot Oil & Gas Ltd',
            'APA Group',
            'Australian Potash Ltd',
            'Apn Property Group',
            'AP Eagers Ltd',
            'Austpac Resources NL',
            'Australian Primary Hemp Ltd',
            'Australian Pharmaceutical Industries Ltd',
            'Antipodes Global Investment Company Ltd',
            'Afterpay Ltd',
            'Appsvillage Australia Ltd',
            'Aims Property Securities Fund',
            'Appen Ltd',
            'Aspen Group',
            'Australian Pacific Coal Ltd',
            'Ausquest Ltd',
            'Alacer Gold Corp',
            'Alicanto Minerals Ltd',
            'Apn Convenience Retail REIT',
            'AQUIS Entertainment Ltd',
            'Alice QUEEN Ltd',
            'Alliance Aviation Services Ltd',
            'Archtis Ltd',
            'Ariadne Australia Ltd',
            'ARB Corporation Ltd',
            'Australian Rural Capital Ltd',
            'Argent Minerals Ltd',
            'Argonaut Resources NL',
            'Arena REIT',
            'Argo Investments Ltd',
            'Ardea Resources Ltd',
            'Aurora Minerals Ltd',
            'Aldoro Resources Ltd',
            'Astro Resources NL',
            'ARQ Group Ltd',
            'Alt Resources Ltd',
            'Arafura Resources Ltd',
            'Artemis Resources Ltd',
            'Angel Seafood Holdings Ltd',
            'Austal Ltd',
            'Autosports Group Ltd',
            'Ashley Services Group Ltd',
            'Betashares Asia Technology Tigers ETF',
            'Anson Resources Ltd',
            'Aspermont Ltd',
            'Australian Silica Quartz Group Ltd',
            'Ausnet Services Ltd',
            'Advanced Share Registry Ltd',
            'ASX Ltd',
            'Atomo Diagnostics Ltd',
            'Altech Chemicals Ltd',
            'Betashares S&P/ASX Australian Technology ETF',
            'Alterity Therapeutics Ltd',
            'Apollo Tourism & Leisure Ltd',
            'Aneka Tambang (Persero) TBK (PT)',
            'Atlas Pearls Ltd',
            'Astron Corporation Ltd',
            'Australis Oil & Gas Ltd',
            'Atrum Coal Ltd',
            'Amplia Therapeutics Ltd',
            'The Agency Group Australia Ltd',
            'Aumake International Ltd',
            'AUB Group Ltd',
            'Ausgold Ltd',
            'Betashares Strong Australian Dollar Fund (Hedge Fund)',
            'Austchina Holdings Ltd',
            'Australian United Investment Company Ltd',
            'Austar Gold Ltd',
            'Ishares Edge MSCI Australia Multifactor ETF',
            'Aurora Property Buy-Write Income Trust',
            'Alara Resources Ltd',
            'Auris Minerals Ltd',
            'Betashares Managed Risk Australian Share Fund',
            'Auteco Minerals Ltd',
            'Australian Mines Ltd',
            'Adveritas Ltd',
            'AVA Risk Group Ltd',
            'Auctus Alternative Investments Ltd',
            'Avecho Biotechnology Ltd',
            'Australian Vintage Ltd',
            'Avita Medical Ltd',
            'Avjennings Ltd',
            'Australian Vanadium Ltd',
            'Aventus Group',
            'Axiom Mining Ltd',
            'Avira Resources Ltd',
            'AVZ Minerals Ltd',
            'Alumina Ltd',
            'Arowana International Ltd',
            'Anova Metals Ltd',
            'Australian Whisky Holdings Ltd',
            'Accent Group Ltd',
            'Accelerate Resources Ltd',
            'Archer Materials Ltd',
            'Axiom Properties Ltd',
            'Argo Exploration Ltd',
            'Australian Enhanced Income Fund',
            'A1 Investments & Resources Ltd',
            'Australia United Mining Ltd',
            'Alloy Resources Ltd',
            'Amaysim Australia Ltd',
            'Alta ZINC Ltd',
            'Aurizon Holdings Ltd',
            'AZURE Minerals Ltd',
            'AZURE Health Tech',
            'AZURE Healthcare Ltd',
            'Antipa Minerals Ltd',
            'Bounty Mining Ltd',
            'Blue Sky Alternatives Access Fund Ltd',
            'Bapcor Ltd',
            'Barra Resources Ltd',
            'Bass Oil Ltd',
            'Battery Minerals Ltd',
            'BNK Banking Corporation Ltd',
            'Brisbane Broncos Ltd',
            'Baby Bunting Group Ltd',
            'Betashares Australian Equities Strongbearhedgefund',
            'Betashares US EQ Strong Bear Hdge FND-CRNCY Hdged',
            'BBX Minerals Ltd',
            'Black Cat Syndicate Ltd',
            'Bowen Coking Coal Ltd',
            'Beam Communications Holdings Ltd',
            'BCI Minerals Ltd',
            'Brockman Mining Ltd',
            'Bunji Corporation Ltd',
            'Beacon Minerals Ltd',
            'Bluechiip Ltd',
            'BARD1 Life Sciences Ltd',
            'Bod Australia Ltd',
            'Bardoc Gold Ltd',
            'Black Dragon Gold Corp',
            'Blina Minerals NL',
            'Betashares Australian Equities Bear Hedge Fund',
            'Broo Ltd',
            'Bentley Capital Ltd',
            'Blackearth Minerals NL',
            'Bendigo and Adelaide Bank Ltd',
            'Betmakers Technology Group Ltd',
            'Beston Global Food Company Ltd',
            'Bell Financial Group Ltd',
            'Bega Cheese Ltd',
            'Bellevue Gold Ltd',
            'Briscoe Group Australasia Ltd',
            'Bio-Gene Technology Ltd',
            'Benjamin Hornigold Ltd',
            'Boyuan Holdings Ltd',
            'BHP Group Ltd',
            'Bidenergy Ltd',
            'Ishares Core Cash ETF',
            'Bingo Industries Ltd',
            'Buildingiq, Inc',
            'BIR Financial Ltd',
            'Bisalloy Steel Group Ltd',
            'Biotron Ltd',
            'BKI Investment Company Ltd',
            'Blackmores Ltd',
            'Black Rock Mining Ltd',
            'Brickworks Ltd',
            'Berkeley Energia Ltd',
            'Blue Sky Alternative Investments Ltd',
            'Boral Ltd',
            'Bluglass Ltd',
            'Blackham Resources Ltd',
            'Blue Energy Ltd',
            'Blossomvale Holdings Ltd',
            'Beacon Lighting Group Ltd',
            'Boart Longyear Ltd',
            'BLAZE International Ltd',
            'BMG Resources Ltd',
            'Baumart Holdings Ltd',
            'Bannerman Resources Ltd',
            'Betashares Legg Mason Australian Bond Fund (Managed Fund)',
            'Betashares Global Banks ETF - Currency Hedged',
            'Big Star Energy Ltd',
            'Bionomics Ltd',
            'Bulletin Resources Ltd',
            'Boadicea Resources Ltd',
            'Bougainville Copper Ltd',
            'Boss Resources Ltd',
            'Boom Logistics Ltd',
            'SPDR S&P/ASX Australian Bond Fund',
            'Bank of Queensland Ltd',
            'Botanix Pharmaceuticals Ltd',
            'BPH Energy Ltd',
            'Broken Hill Prospecting Ltd',
            'Babylon Pump & Power Ltd',
            'Beach Energy Ltd',
            'Breaker Resources NL',
            'Breville Group Ltd',
            'Big River Industries Ltd',
            'Brookside Energy Ltd',
            'Bathurst Resources Ltd',
            'Brainchip Holdings Ltd',
            'Buru Energy Ltd',
            'Big River Gold Ltd',
            'BSA Ltd',
            'Base Resources Ltd',
            'Bluescope Steel Ltd',
            'Bass Metals Ltd',
            'Black Star Petroleum Ltd',
            'Bassari Resources Ltd',
            'Blackstone Minerals Ltd',
            'BTC Health Ltd',
            'Bigtincan Holdings Ltd',
            'Bailador Technology Investments Ltd',
            'Bubs Australia Ltd',
            'Buddy Technologies Ltd',
            'Buderim Group Ltd',
            'Buxton Resources Ltd',
            'Bounty Oil & Gas NL',
            'Bravura Solutions Ltd',
            'Blackwall Ltd',
            'BWP Trust',
            'Blackwall Property Trust',
            'BWX Ltd',
            'Brambles Ltd',
            'Bioxyne Ltd',
            'Byron Energy Ltd',
            'Bryah Resources Ltd',
            'Beyond International Ltd',
            'Copper Mountain Mining Corporation',
            'Coassets Ltd',
            'Capral Ltd',
            'Caeneus Minerals Ltd',
            'Cannindah Resources Ltd',
            'Centrepoint Alliance Ltd',
            'Cape Range Ltd',
            'Calidus Resources Ltd',
            'Capitol Health Ltd',
            'Clime Capital Ltd',
            'Cann Group Ltd',
            'Carpentaria Resources Ltd',
            'CAQ Holdings Ltd',
            'Carsales.com Ltd',
            'Catapult Group International Ltd',
            'Cronos Australia Ltd',
            'Carnavale Resources Ltd',
            'Canyon Resources Ltd',
            'Cazaly Resources Ltd',
            'Commonwealth Bank of Australia',
            'Cobre Ltd',
            'Carbon Revolution Ltd',
            'Canterbury Resources Ltd',
            'Change Financial Ltd',
            'Carnegie Clean Energy Ltd',
            'Commschoice Group Ltd',
            'County International Ltd',
            'Coca-Cola Amatil Ltd',
            'Credit Corp Group Ltd',
            'Cash Converters International',
            'City Chic Collective Ltd',
            'Castillo Copper Ltd',
            'Cordish Dixon Private Equity Fund I',
            'Cordish Dixon Private Equity Fund Ii',
            'Cordish Dixon Private Equity Fund Iii',
            'Codan Ltd',
            'Cardno Ltd',
            'Chongherr Investments Ltd',
            'Cadence Capital Ltd',
            'Carindale Property Trust',
            'Castle Minerals Ltd',
            'Cardinal Resources Ltd',
            'Cardiex Ltd',
            'Cellmid Ltd',
            'Calima Energy Ltd',
            'Challenger Exploration Ltd',
            'Contact Energy Ltd',
            'Vaneck Vectors Ftse China A50 ETF',
            'Cape Lambert Resources Ltd',
            'Cfoam Ltd',
            'Carbonxt Group Ltd',
            'Contango Asset Management Ltd',
            'Cann Global Ltd',
            'Costa Group Holdings Ltd',
            'Challenger Ltd',
            'The Citadel Group Ltd',
            'Cougar Metals NL',
            'Crater Gold Mining Ltd',
            'CPT Global Ltd',
            'CML Group Ltd',
            'Cogstate Ltd',
            'Charter Hall Group',
            'Cohiba Minerals Ltd',
            'Chalice Gold Mines Ltd',
            'Chesser Resources Ltd',
            'Credit Intelligence Ltd',
            'Champion Iron Ltd',
            'Contango Income Generator Ltd',
            'Ci Resources Ltd',
            'Cimic Group Ltd',
            'Carlton Investments Ltd',
            'Carlton Investments Ltd',
            'Connected Io Ltd',
            'Centuria Industrial REIT',
            'Clime Investment Management Ltd',
            'Cokal Ltd',
            'Collins Foods Ltd',
            'Class Ltd',
            'Collaborate Corporation Ltd',
            'Celsius Resources Ltd',
            'Candy Club Holdings Ltd',
            'Concentrated Leaders Fund Ltd',
            'Collection House Ltd',
            'Croplogic Ltd',
            'Clean TEQ Holdings Ltd',
            'Cellnet Group Ltd',
            'Clover Corporation Ltd',
            'Charter Hall Long Wale REIT',
            'Cti Logistics Ltd',
            'Classic Minerals Ltd',
            'Coolgardie Minerals Ltd',
            'Crowd Media Holdings Ltd',
            'China Magnesium Corporation Ltd',
            'Cassius Mining Ltd',
            'Chase Mining Corporation Ltd',
            'Capricorn Metals Ltd',
            'Compumedics Ltd',
            'Cromwell Property Group',
            'Carnaby Resources Ltd',
            'Vaneck Vectors China New Economy ETF',
            'Centuria Capital Group',
            'Conico Ltd',
            'Celamin Holdings Ltd',
            'Chorus Ltd',
            'Cirrus Networks Holdings Ltd',
            'Cobalt Blue Holdings Ltd',
            'Cooper Energy Ltd',
            'Centuria Office REIT',
            'Consolidated Operations Group Ltd',
            'Cochlear Ltd',
            'Comet Ridge Ltd',
            'Coles Group Ltd',
            'Corum Group Ltd',
            'ETFs Global Core Infrastructure ETF',
            'Cosol Ltd',
            'Coppermoly Ltd',
            'Cannpal Animal Therapeutics Ltd',
            'Creso Pharma Ltd',
            'Cipherpoint Ltd',
            'Computershare Ltd',
            'Clearvue Technologies Ltd',
            'Charter Hall Social Infrastructure REIT',
            'Charter Hall Retail REIT',
            'Constellation Resources Ltd',
            'Carbine Resources Ltd',
            'Betashares Australian Investment Grade Corporate Bond ETF',
            'Comet Resources Ltd',
            'Carbon Minerals Ltd',
            'Coronado Global Resources Inc',
            'Cirralto Ltd',
            'Caprice Resources Ltd',
            'Consolidated Tin Mines Ltd',
            'Copper Strike Ltd',
            'CSL Ltd',
            'CSR Ltd',
            'Clean Seas Seafood Ltd',
            'Castile Resources Ltd',
            'CCP Technologies Ltd',
            'Corporate Travel Management Ltd',
            'Cryosite Ltd',
            'Centaurus Metals Ltd',
            'Citigold Corporation Ltd',
            'Central Petroleum Ltd',
            'Caltex Australia Ltd',
            'CUE Energy Resources Ltd',
            'Cullen Resources Ltd',
            'Countplus Ltd',
            'ETFs S&P Biotech ETF',
            'Clinuvel Pharmaceuticals Ltd',
            'Crossland Strategic Metals Ltd',
            'CV Check Ltd',
            'CVC Ltd',
            'Contrarian Value Fund Ltd',
            'Civmec Ltd',
            'Carnarvon Petroleum Ltd',
            'Cervantes Corporation Ltd',
            'Caravel Minerals Ltd',
            'Clearview Wealth Ltd',
            'Chant West Holdings Ltd',
            'Crown Resorts Ltd',
            'Cedar Woods Properties Ltd',
            'Carawine Resources Ltd',
            'Cleanaway Waste Management Ltd',
            'Cashwerkz Ltd',
            'CALIX Ltd',
            'Centrex Metals Ltd',
            'Core Lithium Ltd',
            'Cauldron Energy Ltd',
            'Cradle Resources Ltd',
            'Connexion Telematics Ltd',
            'CYGNUS Gold Ltd',
            'Cyclopharm Ltd',
            'Coventry Group Ltd',
            'Catalyst Metals Ltd',
            'Cyprium Metals Ltd',
            'Cynata Therapeutics Ltd',
            'CYCLIQ Group Ltd',
            'Cassini Resources Ltd',
            'Consolidated ZINC Ltd',
            'Corazon Mining Ltd',
            'Coziron Resources Ltd',
            'Delaware Thirteen Ltd',
            'Duxton Water Ltd',
            'Discovery Africa Ltd',
            'Dampier Gold Ltd',
            'Davenport Resources Ltd',
            'Betashares Diversified Balanced ETF',
            'Duxton Broadacre Farms Ltd',
            'Digitalx Ltd',
            'Decmil Group Ltd',
            'Domacom Ltd',
            'Dacian Gold Ltd',
            'Discovex Resources Ltd',
            '3D Resources Ltd',
            'Dicker Data Ltd',
            'Datadot Technology Ltd',
            'De Grey Mining Ltd',
            'De.Mem Ltd',
            'DEVEX Resources Ltd',
            'Dongfang Modern Agriculture Holding Group Ltd',
            'Betashares Diversified Growth ETF',
            'Desane Group Holdings Ltd',
            'DGO Gold Ltd',
            'DGR Global Ltd',
            'Domain Holdings Australia Ltd',
            'Betashares Diversified High Growth ETF',
            'Dark Horse Resources Ltd',
            'Ubs IQ Morningstar Australia Dividend Yield ETF',
            'SPDR Dow Jones Global Real Estate Fund',
            'Djerriwarrh Investments Ltd',
            'Duketon Mining Ltd',
            'Delecta Ltd',
            'Dome Gold Mines Ltd',
            'Dragon Mountain Gold Ltd',
            'AMP Capital Dynamic Markets Fund (Hedge Fund)',
            'Dominos PIZZA Enterprises Ltd',
            'Donaco International Ltd',
            'Danakali Ltd',
            'Doriemus Plc',
            'Downer Edi Ltd',
            'Dreadnought Resources Ltd',
            'Droneshield Ltd',
            'Betashares Global Healthcare ETF - Currency Hedged',
            'Diatreme Resources Ltd',
            'Dropsuite Ltd',
            'Damstra Holdings Ltd',
            'DTI Group Ltd',
            'Data#3 Ltd',
            'Dart Mining NL',
            'Dateline Resources Ltd',
            'Dragontail Systems Ltd',
            'DOTZ Nano Ltd',
            'Dubber Corporation Ltd',
            'Diversified United Investment Ltd',
            'Dorsavi Ltd',
            'Devine Ltd',
            'Digital Wine Ventures Ltd',
            'DWS Ltd',
            'Dimerix Ltd',
            'DXN Ltd',
            'Dexus',
            'Deep Yellow Ltd',
            'Betashares Diversified Conservative Income ETF',
            'Element 25 Ltd',
            'Eon NRG Ltd',
            'E2 Metals Ltd',
            'Evans & Partners Asia Fund',
            'Ellerston Asian Investments Ltd',
            'Easton Investments Ltd',
            'Energy Action Ltd',
            'Eumundi Group Ltd',
            'Vaneck Emerging Inc Opportunities Active ETF (Managed Fund)',
            'Ebos Group Ltd',
            'Elanor Commercial Property Fund',
            'Ecargo Holdings Ltd',
            'Excelsior Capital Ltd',
            'ECP Emerging Growth Ltd',
            'ECS Botanics Holdings Ltd',
            'Environmental Clean Technologies Ltd',
            'Eclipx Group Ltd',
            'Evans Dixon Ltd',
            'Eildon Capital Fund',
            'Eden Innovations Ltd',
            'Empire Energy Group Ltd',
            'East Energy Resources Ltd',
            'Betashares Euro ETF',
            'Eastern Iron Ltd',
            'Evans & Partners Australian Flagship Fund',
            'Evans & Partners Global Disruption Fund',
            'Evans & Partners Global Flagship Fund',
            'Enero Group Ltd',
            'Eureka Group Holdings Ltd',
            'Ellerston Global Investments Ltd',
            'Environmental Group Ltd (the)',
            'Engenco Ltd',
            'Empire Oil & Gas NL',
            'Ecograf Ltd',
            'Energy Technologies Ltd',
            'Estia Health Ltd',
            'Eagle Health Holdings Ltd',
            'Emeco Holdings Ltd',
            'Ehr Resources Ltd',
            'Einvest Income Generator Fund (Managed Fund)',
            'Betashares Legg Mason Equity Income Fund (Managed Fund)',
            'Elders Ltd',
            'Elmore Ltd',
            'Elmo Software Ltd',
            'Elsight Ltd',
            'Elementos Ltd',
            'ELLEX Medical Lasers Ltd',
            'Emerge Gaming Ltd',
            'Eagle Mountain Mining Ltd',
            'Embelton Ltd',
            'Emerald Clinics Ltd',
            'Energy Metals Ltd',
            'European Metals Holdings Ltd',
            'Vaneck Vectors MSCI Multifactor Emerging Markets Equity ETF',
            'EML Payments Ltd',
            'Betashares Legg Mason Emerging Markets Fund (Managed Fund)',
            'Euro Manganese Inc',
            'Emperor Energy Ltd',
            'Emerald Resources NL',
            'Emetals Ltd',
            'EMU NL',
            'EMU NL',
            'Emvision Medical Devices Ltd',
            'Engage:BDR Ltd',
            'Ensurance Ltd',
            'Eneabba Gas Ltd',
            'Enevis Ltd',
            'Elanor Investors Group',
            'Encounter Resources Ltd',
            'Enterprise Metals Ltd',
            'Enegex Ltd',
            'Ecofibre Ltd',
            'Energy One Ltd',
            'EOR Group Ltd',
            'Electro Optic Systems Holdings Ltd',
            'Empired Ltd',
            'Eclipse Metals Ltd',
            'EQUUS Mining Ltd',
            'EQT Holdings Ltd',
            'Equatorial Resources Ltd',
            'Energy Resources of Australia Ltd',
            'Elanor Retail Property Fund',
            'Eneco Refresh Ltd',
            'Empire Resources Ltd',
            'Emmerson Resources Ltd',
            'Exore Resources Ltd',
            'Esense-Lab Ltd',
            'Vaneck Vectors MSCI International Sustainable Equity ETF',
            'Esports Mogul Ltd',
            'Etherstack Plc',
            'Eco Systems Ltd',
            'Estrella Resources Ltd',
            'ETFs Euro STOXX 50 ETF',
            'Ubs IQ Morningstar Australia Quality ETF',
            'Betashares Global Sustainability Leaders ETF',
            'ETFs Group',
            'ETFs Group',
            'ETFs Group',
            'ETFs Group',
            'European Cobalt Ltd',
            'European Lithium Ltd',
            'EVE Investments Ltd',
            'Evolution Mining Ltd',
            'Evolve Education Group Ltd',
            'Envirosuite Ltd',
            'Event Hospitality and Entertainment Ltd',
            'EVZ Ltd',
            'Energy World Corporation Ltd',
            'Exopharm Ltd',
            'Betashares Australian Ex-20 Portfolio Diversifier ETF',
            'Elixinol Global Ltd',
            'ENNOX Group Ltd',
            'Experience Co Ltd',
            'Elixir Energy Ltd',
            'EUROZ Ltd',
            'Betashares Ftse 100 ETF',
            'Betashares Australian Sustainability Leaders ETF',
            'Family Insights Group Ltd',
            'ETFs Fang+ ETF',
            'FAR Ltd',
            'First Au Ltd',
            'FBR Ltd',
            'Fletcher Building Ltd',
            'Frontier Capital Group Ltd',
            'Fineos Corporation Holdings Plc',
            'Firstwave Cloud Technology Ltd',
            'Freedom Oil and Gas Ltd',
            'Frontier Digital Ventures Ltd',
            'Frontier Diamonds Ltd',
            'Faster Enterprises Ltd',
            'Fe Investments Group Ltd',
            'Fe Ltd',
            'Fidelity Global Emerging Markets Fund (Managed Fund)',
            'FENIX Resources Ltd',
            'Farmaforce Ltd',
            'Fatfish Blockchain Ltd',
            'FFI Holdings Ltd',
            'Founders First Ltd',
            'Firefly Resources Ltd',
            'Future Generation Global Investment Company Ltd',
            'Flamingo Ai Ltd',
            'First Graphene Ltd',
            'Future Generation Investment Company Ltd',
            'Freehill Mining Ltd',
            'Fiducian Group Ltd',
            'Freedom Insurance Group Ltd',
            'Fiji Kava Ltd',
            'FIN Resources Ltd',
            'Fluence Corporation Ltd',
            'Freelancer Ltd',
            'Vaneck Vectors Australian Floating Rate ETF',
            'Flight Centre Travel Group Ltd',
            'Fortescue Metals Group Ltd',
            'Focus Minerals Ltd',
            'Flinders Mines Ltd',
            'Freedom Foods Group Ltd',
            'Frontier Resources Ltd',
            'The Food Revolution Group Ltd',
            'Betashares Global Agriculture ETF - Currency Hedged',
            'Forager Australian Shares Fund',
            'Fat Prophets Global Contrarian Fund Ltd',
            'Fisher & Paykel Healthcare Corporation Ltd',
            'Fremont Petroleum Corporation Ltd',
            'Fat Prophets Global Property Fund',
            'Finbar Group Ltd',
            'Farm Pride Foods Ltd',
            'Fraser Range Metals Group Ltd',
            'Flexiroam Ltd',
            'FSA Group Ltd',
            'Fonterra Shareholders Fund',
            'Field Solutions Holdings Ltd',
            'Flagship Investments Ltd',
            'Fintech Chain Ltd',
            'Factor Therapeutics Ltd',
            'Fertoz Ltd',
            'Betashares Global Energy Companies ETF - Currency Hedged',
            'Funtastic Ltd',
            'Fleetwood Corporation Ltd',
            'Flexigroup Ltd',
            'FYI Resources Ltd',
            'Family ZONE Cyber Safety Ltd',
            'Fitzroy River Corporation Ltd',
            'Galena Mining Ltd',
            'Golden Mile Resources Ltd',
            'Galileo Mining Ltd',
            'Gale Pacific Ltd',
            'State GAS Ltd',
            'Globe Metals & Mining Ltd',
            'GBM Gold Ltd',
            'Betashares Sustainability Leaders DVRSFD Bond ETF - Cur HDG',
            'Global Petroleum Ltd',
            'Great Boulder Resources Ltd',
            'GBM Resources Ltd',
            'Glennon Small Companies Ltd',
            'Gryphon Capital Income Trust',
            'Golden Cross Resources Ltd',
            'Gascoyne Resources Ltd',
            'Garda Property Group',
            'Generation Development Group Ltd',
            'GDI Property Group',
            'Vaneck Vectors Gold Miners ETF',
            'Betashares Geared Australian Equity Fund (Hedge Fund)',
            'Golden Deeps Ltd',
            'G8 Education Ltd',
            'Genesis Resources Ltd',
            'Global Energy Ventures Ltd',
            'Global Fortune Investment Ltd',
            'Global Masters Fund Ltd',
            'Grand Gulf Energy Ltd',
            'Greenland Minerals Ltd',
            'Betashares Geared US EQ FND Currency Hdged HDG FND',
            'GAS2GRID Ltd',
            'Gibb River Diamonds Ltd',
            'Gi Dynamics, Inc',
            'Gladiator Resources Ltd',
            'Globe International Ltd',
            'GLG Corp Ltd',
            'Global Health Ltd',
            'AMP Cap Global Infrastructure Sec Fund',
            'Galilee Energy Ltd',
            'Galan Lithium Ltd',
            'Global Oil & Gas Ltd',
            'Genworth Mortgage Insurance Australia Ltd',
            'Gulf Manganese Corporation Ltd',
            'Genesis Minerals Ltd',
            'GME Resources Ltd',
            'Goodman Group',
            'Gateway Mining Ltd',
            'Gold Mountain Ltd',
            'Golden Rim Resources Ltd',
            'G Medical Innovations Holdings Ltd',
            'Graincorp Ltd',
            'Genesis Energy Ltd',
            'GR Engineering Services Ltd',
            'Great Northern Minerals Ltd',
            'GENEX Power Ltd',
            'The GO2 People Ltd',
            'ETFs Metal Securities Australia Ltd',
            'Gooroo Ventures Ltd',
            'Gold Road Resources Ltd',
            'SPDR S&P/ASX Australian Government Bond Fund',
            'Gowing Bros Ltd',
            'Growthpoint Properties Australia',
            'Geopacific Resources Ltd',
            'GPS Alliance Holdings Ltd',
            'GPT Group',
            'Graphex Mining Ltd',
            'Gage Roads Brewing Co Ltd',
            'Godolphin Resources Ltd',
            'Vaneck Vectors MSCI Australian Sustainable Equity ETF',
            'Schroder Real Return Fund (Managed Fund)',
            'Grange Resources Ltd',
            'Greenvale Energy Ltd',
            'Golden State Mining Ltd',
            'Great Southern Mining Ltd',
            'Genetic Signatures Ltd',
            'Getswift Ltd',
            'Great Western Exploration Ltd',
            'Genetic Technologies Ltd',
            'Gentrack Group Ltd',
            'GTN Ltd',
            'Gti Resources Ltd',
            'G.U.D. Holdings Ltd',
            'Gullewa Ltd',
            'Global Value Fund Ltd',
            'GWA Group Ltd',
            'GWR Group Ltd',
            'Galaxy Resources Ltd',
            'Betashares Global Cybersecurity ETF',
            'Hastings Technology Metals Ltd',
            'Havilah Resources Ltd',
            'Hawthorn Resources Ltd',
            'Betashares Active Australian Hybrids Fund (Managed Fund)',
            'Hydrocarbon Dynamics Ltd',
            'Hot Chili Ltd',
            'Holista Colltech Ltd',
            'Helios Energy Ltd',
            'Betashares Europe ETF-Currency Hedged',
            'Highfield Resources Ltd',
            'Heartland Group Holdings Ltd',
            'Hudson Investment Group Ltd',
            'High Grade Metals Ltd',
            'Hillgrove Resources Ltd',
            'Hampton Hill Mining NL',
            'HHY Fund',
            'Hills Ltd',
            'Hipo Resources Ltd',
            'Hitech Group Australia Ltd',
            'Betashares Japan ETF-Currency Hedged',
            'Healthia Ltd',
            'Helloworld Travel Ltd',
            'Healius Ltd',
            'HELIX Resources Ltd',
            'Hearts and Minds Investments Ltd',
            'Home Consortium',
            'Heramed Ltd',
            'Hearmeout Ltd',
            'Hammer Metals Ltd',
            'HGL Ltd',
            'Hannans Ltd',
            'Hawkley Oil and Gas Ltd',
            'Horseshoe Metals Ltd',
            'Hotcopper Holdings Ltd',
            'Hotel Property Investments',
            'High Peak Royalties Ltd',
            'HRL Holdings Ltd',
            'Horizon Gold Ltd',
            'Heron Resources Ltd',
            'Horizon Minerals Ltd',
            'Homestay Care Ltd',
            'Hansen Technologies Ltd',
            'HT&E Ltd',
            'Harris Technology Group Ltd',
            'Hutchison Telecommunications (Australia) Ltd',
            'Harvest Technology Group Ltd',
            'HUB24 Ltd',
            'Huon Aquaculture Group Ltd',
            'Happy Valley Nutrition Ltd',
            'Harvey Norman Holdings Ltd',
            'Betashares Australian Dividend Harvester Fund (Managed Fund)',
            'Houston We Have Ltd',
            'Hawkstone Mining Ltd',
            'Hexagon Energy Materials Ltd',
            'HYDRIX Ltd',
            'Horizon Oil Ltd',
            'HAZER Group Ltd',
            'Ishares Asia 50 ETF',
            'Ishares Core Composite Bond ETF',
            'Insurance Australia Group Ltd',
            'Intiger Group Ltd',
            'Investec Australia Property Fund',
            'Ironbark Capital Ltd',
            'Ironbark ZINC Ltd',
            'Imagion Biosystems Ltd',
            'Icetana Ltd',
            'Inca Minerals Ltd',
            'Icandy Interactive Ltd',
            'Icon Energy Ltd',
            'Icar Asia Ltd',
            'Icsglobal Ltd',
            'Icollege Ltd',
            'Isentric Ltd',
            'Identitii Ltd',
            'Indiana Resources Ltd',
            'IDT Australia Ltd',
            'Integral Diagnostics Ltd',
            'Indoor Skydive Australia Group Ltd',
            'Intra Energy Corporation Ltd',
            'Idp Education Ltd',
            'Ishares MSCI Emerging Markets ETF',
            'International Equities Corporation Ltd',
            'Ishares Europe ETF',
            'IOOF Holdings Ltd',
            'Infomedia Ltd',
            'Infigen Energy',
            'Vaneck Vectors Ftse Global Infrastructure (Hedged) ETF',
            'Infratil Ltd',
            'Ishares Treasury ETF',
            'Integrated Green Energy Solutions Ltd',
            'Ive Group Ltd',
            'Ignite Ltd',
            'IGO Ltd',
            'Ishares Core Global Corporate Bond(Aud Hedged) ETF',
            'Ishares S&P/ASX Dividend Opportunities ETF',
            'Ishares JP Morgan Usd Emerging MKT BND Aud HDG ETF',
            'Ishares Global High Yield Bond (Aud Hedged) ETF',
            'Impression Healthcare Ltd',
            'Ishares Global 100 Aud Hedged ETF',
            'Intellihr Ltd',
            'Ishares S&P 500 Aud Hedged ETF',
            'Ishares Core MSCI World All Cap (Aud Hedged) ETF',
            'Betashares India Quality ETF',
            'Ishares S&P Mid-Cap ETF',
            'Ishares MSCI Japan ETF',
            'Ishares S&P Small-Cap ETF',
            'Ikegps Group Ltd',
            'Ishares MSCI South Korea ETF',
            'Ikwezi Mining Ltd',
            'Ishares Government Inflation ETF',
            'Ishares S&P/ASX 20 ETF',
            'Iluka Resources Ltd',
            'Image Resources NL',
            'Immuron Ltd',
            'IMDEX Ltd',
            'Imexhs Ltd',
            'Immutep Ltd',
            'Einvest Future Impact Small Caps Fund (Managed Fund)',
            'Imricor Medical Systems, Inc',
            'Impelus Ltd',
            'Imugene Ltd',
            'Ingenia Communities Group',
            'Betashares Global Income Leaders ETF',
            'Intelligent Investor Ethical Share Fund (Managed Fund)',
            'Infinity Lithium Corporation Ltd',
            'Inghams Group Ltd',
            'Intelligent Investor Aus Equity Income Fund (Managed Fund)',
            'Incentiapay Ltd',
            'Ioneer Ltd',
            'Investsmart Group Ltd',
            'Iodm Ltd',
            'Ishares Global 100 ETF',
            'Ishares Core S&P/ASX 200 ETF',
            'Integrated Payment Technologies Ltd',
            'IPB Petroleum Ltd',
            'Imperial Pacific Ltd',
            'Impedimed Ltd',
            'IPH Ltd',
            'Incitec Pivot Ltd',
            'Impact Minerals Ltd',
            'IQ3CORP Ltd',
            'Iron Road Ltd',
            'Iress Ltd',
            'Integrated Research Ltd',
            'I Synergy Group Ltd',
            'Isentia Group Ltd',
            'Ishares Enhanced Cash ETF',
            'Ishares S&P/ASX Small Ordinaries ETF',
            'Iselect Ltd',
            'Isignthis Ltd',
            'Intega Group Ltd',
            'Invocare Ltd',
            'Ishares MSCI Eafe ETF',
            'Invigor Group Ltd',
            'Invitrocue Ltd',
            'Investigator Resources Ltd',
            'Inventis Ltd',
            'Ishares S&P 500 ETF',
            'Invion Ltd',
            'Invictus Energy Ltd',
            'Ishares Core MSCI World All Cap ETF',
            'INVEX Therapeutics Ltd',
            'Ishares Global Consumer Staples ETF',
            'Ishares Global Healthcare ETF',
            'Ionic Rare EARTHS Ltd',
            'Ixup Ltd',
            'Ishares China Large-Cap ETF',
            'Jameson Resources Ltd',
            'Janison Education Group Ltd',
            'Jatenergy Ltd',
            'Jayride Group Ltd',
            'JB Hi-Fi Ltd',
            'Jiancheng International Group Ltd',
            'Jcurve Solutions Ltd',
            'Jadar Resources Ltd',
            'Japara Healthcare Ltd',
            'Janus Henderson Group Plc',
            'JAYEX Healthcare Ltd',
            'James Hardie Industries Plc',
            'Jumbo Interactive Ltd',
            'Jack-in Group Ltd',
            'Jiajiafu Modern Agriculture Ltd',
            'Jacka Resources Ltd',
            'Johns LYNG Group Ltd',
            'Jupiter Mines Ltd',
            'Jupiter Energy Ltd',
            'Jindalee Resources Ltd',
            'Jervois Mining Ltd',
            'Jaxsta Ltd',
            'Joyce Corporation Ltd',
            'K2FLY Ltd',
            'Kairos Minerals Ltd',
            'K2 Asset Management Holdings Ltd',
            'Karoon Energy Ltd',
            'Kasbah Resources Ltd',
            'Katana Capital Ltd',
            'Kaiser Reef Ltd',
            'Keybridge Capital Ltd',
            'Kingsgate Consolidated Ltd',
            'KEY Petroleum Ltd',
            'Kogi Iron Ltd',
            'Kula Gold Ltd',
            'KGL Resources Ltd',
            'Kalnorth Gold Mines Ltd',
            'Kogan.com Ltd',
            'KIN Mining NL',
            'King Island Scheelite Ltd',
            'KKR Credit Income Fund',
            'Kollakorn Corporation Ltd',
            'Kinetiko Energy Ltd',
            'Kirkland Lake Gold Ltd',
            'Kalium Lakes Ltd',
            'Kingsland Global Ltd',
            'Kaili Resources Ltd',
            'Kathmandu Holdings Ltd',
            'Kip Mcgrath Education Centres Ltd',
            'Kopore Metals Ltd',
            'Koon Holdings Ltd',
            'Kneomedia Ltd',
            'Knosys Ltd',
            'Korab Resources Ltd',
            'Korvest Ltd',
            'Kore Potash Plc',
            'Kazakhstan Potash Corporation Ltd',
            'Kina Petroleum Corporation',
            'Kelly Partners Group Holdings Ltd',
            'Kalina Power Ltd',
            'Kangaroo Island Plantation Timbers Ltd',
            'Kingsrose Mining Ltd',
            'King River Resources Ltd',
            'Kresta Holdings Ltd',
            'K & S Corporation Ltd',
            'Kina Securities Ltd',
            'K2 Australian Small Cap Fund (Hedge Fund)',
            'Kingston Resources Ltd',
            'Kleos Space S.A',
            'Krakatoa Resources Ltd',
            'Keytone Dairy Corporation Ltd',
            'K2 Energy Ltd',
            'K-Tig Ltd',
            'Kingwest Resources Ltd',
            'KYCKR Ltd',
            'KAZIA Therapeutics Ltd',
            'Kalamazoo Resources Ltd',
            'Latam Autos Ltd',
            'Laramide Resources Ltd',
            'Lindsay Australia Ltd',
            'Lawfinance Ltd',
            'Laserbond Ltd',
            'LBT Innovations Ltd',
            'Latitude Consolidated Ltd',
            'London City Equities Ltd',
            'Leigh Creek Energy Ltd',
            'Los Cerros Ltd',
            'Logicamms Ltd',
            'Living Cell Technologies Ltd',
            'Legacy Iron Ore Ltd',
            'Legend Mining Ltd',
            'Ale Property Group',
            'Leaf Resources Ltd',
            'Lefroy Exploration Ltd',
            'Little Green Pharma Ltd',
            'Lanka Graphite Ltd',
            'Lionhub Group Ltd',
            'Land & Homes Group Ltd',
            'Lithium Consolidated Ltd',
            'Lifestyle Communities Ltd',
            'Lindian Resources Ltd',
            'Lion Energy Ltd',
            'Lithium Australia NL',
            'Lake Resources N.L.',
            'Lakes Oil NL',
            'Lendlease Group',
            'Lion One Metals Ltd',
            'Limeade, Inc',
            'Latrobe Magnesium Ltd',
            'Lincoln Minerals Ltd',
            'Liquefied Natural Gas Ltd',
            'Link Administration Holdings Ltd',
            'Linius Technologies Ltd',
            'Laneway Resources Ltd',
            'Lucapa Diamond Company Ltd',
            'Longtable Group Ltd',
            'Lotus Resources Ltd',
            'Lovisa Holdings Ltd',
            'Lepidico Ltd',
            'Lepidico Ltd',
            'Locality Planning Energy Holdings Ltd',
            'Lithium Power International Ltd',
            'Lustrum Minerals Ltd',
            'Latin Resources Ltd',
            'Lowell Resources Fund',
            'Lachlan Star Ltd',
            'L1 Long Short Fund Ltd',
            'Lifespot Health Ltd',
            'Lodestar Minerals Ltd',
            'Lion Selection Group Ltd',
            'Liontown Resources Ltd',
            'Love Group Global Ltd',
            'Livehire Ltd',
            'Livetiles Ltd',
            'Lynas Corporation Ltd',
            'Lycopodium Ltd',
            'MACH7 Technologies Ltd',
            'M8 Sustainable Ltd',
            'Monash Absolute Investment Company Ltd',
            'Mader Group Ltd',
            'Magmatic Resources Ltd',
            'Macmahon Holdings Ltd',
            'Mainstream Group Holdings Ltd',
            'Microequities Asset Management Group Ltd',
            'Mandrake Resources Ltd',
            'Macquarie Telecom Group Ltd',
            'Matsa Resources Ltd',
            'Magnetic Resources NL',
            'Magnetic Resources NL',
            'Milliniums Alternatives Fund',
            'Melbana Energy Ltd',
            'Metal Bank Ltd',
            'Mobecom Ltd',
            'Murray Cod Australia Ltd',
            'MCB Resources Ltd',
            'Matrix Composites & Engineering Ltd',
            'MC Mining Ltd',
            'Mcphersons Ltd',
            'Mincor Resources NL',
            'Metalicity Ltd',
            'Mariner Corporation Ltd',
            'Mercury NZ Ltd',
            'Medlab Clinical Ltd',
            'Middle Island Resources Ltd',
            'Medadvisor Ltd',
            'Mindax Ltd',
            'Mcgrath Ltd',
            'Medibio Ltd',
            'Morphic Ethical Equities Fund Ltd',
            'Meteoric Resources NL',
            'Metgasco Ltd',
            'Memphasys Ltd',
            'Minotaur Exploration Ltd',
            'Metlifecare Limited Foreign Exempt NZX',
            'Marmota Ltd',
            'Marenica Energy Ltd',
            'Meridian Energy Ltd',
            'Mayfield Childcare Ltd',
            'MFF Capital Investments Ltd',
            'Magellan Financial Group Ltd',
            'MG Unit Trust',
            'Magellan Global Equities Fund (Managed Fund)',
            'Magellan Global Trust',
            'Magontec Ltd',
            'Mirvac Group',
            'Magnetite Mines Ltd',
            'Magnum Mining and Exploration Ltd',
            'Musgrave Minerals Ltd',
            'Mount Gibson Iron Ltd',
            'Medigard Ltd',
            'Manhattan Corporation Ltd',
            'Millennium Ltd',
            'Magellan Global Equities Fund(Currency Hedged)(MF)',
            'Magellan High Conviction Trust',
            'Merchant House International Ltd',
            'Michael Hill International Ltd',
            'Magellan Infrastructure Fund (Currency Hedged)(Managed Fund)',
            'MNC Media Investment Ltd',
            'Millennium Services Group Ltd',
            'Mineral Resources Ltd',
            'Macarthur Minerals Ltd',
            'Mirrabooka Investments Ltd',
            'Mejority Capital Ltd',
            'Mako Gold Ltd',
            'Maca Ltd',
            'Mali Lithium Ltd',
            'Metallica Minerals Ltd',
            'Metals Australia Ltd',
            'Milton Corporation Ltd',
            'Metals X Ltd',
            'Moneyme Ltd',
            'Metro Mining Ltd',
            'MMJ Group Holdings Ltd',
            'Medusa Mining Ltd',
            'Marley Spoon AG',
            'Mec Resources Ltd',
            'Mcmillan Shakespeare Ltd',
            'Minbos Resources Ltd',
            'Monadelphous Group Ltd',
            'MNF Group Ltd',
            'Betashares Global Gold Miners ETF - Currency Hedged',
            'Magnis Energy Technologies Ltd',
            'Mint Payments Ltd',
            'MONEY3 Corporation Ltd',
            'Vaneck Vectors Morningstar Wide Moat ETF',
            'Mobilicom Ltd',
            'Mortgage Choice Ltd',
            'Moelis Australia Ltd',
            'Montgomery Global Equities Fund (Managed Fund)',
            'Moho Resources Ltd',
            'Ubs IQ Cash ETF',
            'MOQ Ltd',
            'MCP Income Opportunities Trust',
            'Millennium Minerals Ltd',
            'Mosaic Brands Ltd',
            'Megaport Ltd',
            'Mediland Pharm Ltd',
            'Medibank Private Ltd',
            'Molopo Energy Ltd',
            'Metro Performance Glass Ltd',
            'Mpower Group Ltd',
            'MSL Solutions Ltd',
            'Mustera Property Group Ltd',
            'Macquarie Group Ltd',
            'Marquee Resources Ltd',
            'Mineral Commodities Ltd',
            'Mount Ridley Mines Ltd',
            'Murray River Organics Group Ltd',
            'Mayur Resources Ltd',
            'Mma Offshore Ltd',
            'MRG Metals Ltd',
            'Minrex Resources Ltd',
            'Moreton Resources Ltd',
            'Mont Royal Resources Ltd',
            'Mesoblast Ltd',
            'Metalsearch Ltd',
            'MCS Services Ltd',
            'Multistack International Ltd',
            'MSM Corporation International Ltd',
            'Manas Resources Ltd',
            'Morningstar International Shares Active ETF (Managed Fund)',
            'Mitchell Services Ltd',
            'Mount Burgess Mining NL',
            'Metalstech Ltd',
            'Mithril Resources Ltd',
            'Manalto Ltd',
            'Motorcycle Holdings Ltd',
            'Metcash Ltd',
            'Vaneck Vectors Australian Property ETF',
            'Vaneck Vectors Australian Banks ETF',
            'Vaneck Vectors S&P/ASX Midcap ETF',
            'Monash Ivf Group Ltd',
            'Ishares Edge MSCI Australia Minimum Volatility ETF',
            'Medical Developments International Ltd',
            'Vaneck Vectors Australian Resources ETF',
            'Vaneck Vectors Small Companies Masters ETF',
            'Vaneck Vectors Australian EQUAL Weight ETF',
            'MGM Wireless Ltd',
            'Midway Ltd',
            'Micro-X Ltd',
            'MGC Pharmaceuticals Ltd',
            'Maxitrans Industries Ltd',
            'Maximus Resources Ltd',
            'MCP Master Income Trust',
            'Mastermyne Group Ltd',
            'Myanmar Metals Ltd',
            'Myfiziq Ltd',
            'Myer Holdings Ltd',
            'Mystate Ltd',
            'Mayne Pharma Group Ltd',
            'MZI Resources Ltd',
            'Matador Mining Ltd',
            'N1 Holdings Ltd',
            'National Australia Bank Ltd',
            'Naos Ex-50 Opportunities Company Ltd',
            'New Age Exploration Ltd',
            'Nagambie Resources Ltd',
            'Namoi Cotton Ltd',
            'Nanosonics Ltd',
            'NB Global Corporate Income Trust',
            'Nanollose Ltd',
            'Naos Emerging Opportunities Company Ltd',
            'Nick Scali Ltd',
            'Netccentric Ltd',
            'Newcrest Mining Ltd',
            'Nucoal Resources Ltd',
            'New Century Resources Ltd',
            'ETFs Reliance India Nifty 50 ETF',
            'Betashares Nasdaq 100 ETF',
            'Nearmap Ltd',
            'Nine Entertainment Co. Holdings Ltd',
            'Nelson Resources Ltd',
            'Netlinkz Ltd',
            'Neuren Pharmaceuticals Ltd',
            'NEW Energy Solar',
            'NGE Capital Ltd',
            'Navigator Global Investments Ltd',
            'Nuenergy Gas Ltd',
            'New Hope Corporation Ltd',
            'Nib Holdings Ltd',
            'Nickel Mines Ltd',
            'Niuminco Group Ltd',
            'NEX Metals Exploration Ltd',
            'Navarre Minerals Ltd',
            'Neometals Ltd',
            '99 Technology Ltd',
            'Norwood Systems Ltd',
            'Novatti Group Ltd',
            'Noxopharm Ltd',
            'Neuroscientific Biopharmaceuticals Ltd',
            'Naos Small Cap Opportunities Company Ltd',
            'New Standard Energy Ltd',
            'National Storage REIT',
            'Northern Star Resources Ltd',
            'NSX Ltd',
            'National Tyre & Wheel Ltd',
            'Neurotech International Ltd',
            'New Talisman Gold Mines Ltd',
            'NTM Gold Ltd',
            'Nitro Software Ltd',
            'Northern Minerals Ltd',
            'Nuchev Ltd',
            'Nufarm Ltd',
            'Nuheara Ltd',
            'Nusantara Resources Ltd',
            'Nova Minerals Ltd',
            'Nvoi Ltd',
            'Nanoveu Ltd',
            'Novonix Ltd',
            'New World Resources Ltd',
            'Norwest Energy NL',
            'Newfield Resources Ltd',
            'NRW Holdings Ltd',
            'Netwealth Group Ltd',
            'Norwest Minerals Ltd',
            'News Corporation',
            'News Corporation',
            'New Energy Minerals Ltd',
            'Nexus Minerals Ltd',
            'Next Science Ltd',
            'NEXTDC Ltd',
            'Nyrada Inc',
            'New Zealand King Salmon Investments Ltd',
            'NZME Ltd',
            'New Zealand Coastal Seafoods Ltd',
            'Oakdale Resources Ltd',
            'Ora Gold Ltd',
            'OBJ Limited',
            'Omni Bridgeway Ltd',
            'Ora Banda Mining Ltd',
            'Oceania Healthcare Ltd',
            'Orthocell Ltd',
            'Objective Corporation Ltd',
            'Orcoda Ltd',
            'Odin Metals Ltd',
            'Odyssey Energy Ltd',
            'Orbital Corporation Ltd',
            'Otto Energy Ltd',
            'Orion Equities Ltd',
            'OILEX Ltd',
            'OFX Group Ltd',
            'Ocean Grown Abalone Ltd',
            'Oceanagold Corporation',
            'Orinoco Gold Ltd',
            'Optiscan Imaging Ltd',
            'Oakajee Corporation Ltd',
            'Okapi Resources Ltd',
            'Oklo Resources Ltd',
            'Oldfields Holdings Ltd',
            'Olivers Real Food Ltd',
            'Openlearning Ltd',
            'Otherlevels Holdings Ltd',
            'Om Holdings Ltd',
            'Ooh!Media Ltd',
            'Oneview Healthcare Plc',
            '1300 Smiles Ltd',
            'Orminex Ltd',
            'Ookami Ltd',
            'Betashares Crude Oil INDEX ETF-Currency Hedged (Synthetic)',
            'Opticomm Ltd',
            'Ophir High Conviction Fund',
            'Opyl Ltd',
            'Opthea Ltd',
            'Openpay Group Ltd',
            'Orora Ltd',
            'Orocobre Ltd',
            'Origin Energy Ltd',
            'Orica Ltd',
            'Orion Metals Ltd',
            'Orion Minerals Ltd',
            'Orecorp Ltd',
            'Oil Search Ltd',
            'Oncosil Medical Ltd',
            'Osprey Medical Inc',
            'Osteopore Ltd',
            'Over the Wire Holdings Ltd',
            'Onevue Holdings Ltd',
            'Oventus Medical Ltd',
            'Ovato Ltd',
            'Octanex Ltd',
            'SPDR S&P/ASX 200 Financials Ex A-REIT Fund',
            'Ozgrowth Ltd',
            'OZ Minerals Ltd',
            'SPDR S&P/ASX 200 Resources Fund',
            'P2P Transport Ltd',
            'Pharmaust Ltd',
            'PATRYS Ltd',
            'Pacific Current Group Ltd',
            'PM Capital Asian Opportunities Fund Ltd',
            'Platinum Asia Investments Ltd',
            'Pacific American Holdings Ltd',
            'Palla Pharma Ltd',
            'Panoramic Resources Ltd',
            'Paradigm Biopharmaceuticals Ltd',
            'Platinum Asia Fund (Quoted Managed Hedge Fund)',
            'Pointsbet Holdings Ltd',
            'Probiotec Ltd',
            'Pacific Bauxite Ltd',
            'Pengana Capital Group Ltd',
            'Property Connect Holdings Ltd',
            'Perpetual Credit Income Trust',
            'Painchek Ltd',
            'Pancontinental Oil & Gas NL',
            'Predictive Discovery Ltd',
            'Pendal Group Ltd',
            'Paladin Energy Ltd',
            'Prairie Mining Ltd',
            'Pengana Private Equity Trust',
            'Perpetual Resources Ltd',
            'Peak Resources Ltd',
            'Pelican Resources Ltd',
            'Peninsula Energy Ltd',
            'Phoslock Environmental Technologies Ltd',
            'Peel Mining Ltd',
            'Prime Financial Group Ltd',
            'Propel Funeral Partners Ltd',
            'Pearl Global Ltd',
            'Paragon Care Ltd',
            'PM Capital Global Opportunities Fund Ltd',
            'Partners Group Global Income Fund',
            'Pact Group Holdings Ltd',
            'Panterra Gold Ltd',
            'Prospa Group Ltd',
            'Platina Resources Ltd',
            'The Pas Group Ltd',
            'Primero Group Ltd',
            'Pilot Energy Ltd',
            'Pengana International Equities Ltd',
            'Perpetual Equity Investment Company Ltd',
            'Peppermint Innovation Ltd',
            'Pinchme.com Inc',
            'Pioneer Resources Ltd',
            'Proteomics International Laboratories Ltd',
            'Platinum International Fund (Quoted Managed Hedge Fund)',
            'Parkd Ltd',
            'Peako Ltd',
            'PKS Holdings Ltd',
            'Plato Income Maximiser Ltd',
            'PLC Financial Solutions Ltd',
            'Piedmont Lithium Ltd',
            'Pilbara Minerals Ltd',
            'Vaneck Vectors Australian Corporate Bond Plus ETF',
            'Pyrolyx AG',
            'Pure Minerals Ltd',
            'Pensana Rare EARTHS Plc',
            'Platinum Capital Ltd',
            'Pro Medicus Ltd',
            'Gold Corporation',
            'Premier Investments Ltd',
            'Pacifico Minerals Ltd',
            'Pioneer Credit Ltd',
            'Pinnacle Investment Management Group Ltd',
            'Paringa Resources Ltd',
            'Pepinnini Lithium Ltd',
            'Pantoro Ltd',
            'Polynovo Ltd',
            'Pacific Star Network Ltd',
            'PNX Metals Ltd',
            'Purifloh Ltd',
            'Podium Minerals Ltd',
            'Poseidon Nickel Ltd',
            'Betashares British Pound ETF',
            'Protean Energy Ltd',
            'Peet Ltd',
            'People Infrastructure Ltd',
            'Pro-Pac Packaging Ltd',
            'Pushpay Holdings Ltd',
            'PPK Group Ltd',
            'Pureprofile Ltd',
            'Praemium Ltd',
            'Perpetual Ltd',
            'Papyrus Australia Ltd',
            'Prominence Energy NL',
            'Perenti Global Ltd',
            'Prophecy International Holdings Ltd',
            'Prime Media Group Ltd',
            'Perseus Mining Ltd',
            'Prodigy Gold NL',
            'Parazero Ltd',
            'Petsec Energy Ltd',
            'Prospect Resources Ltd',
            'PSC Insurance Group Ltd',
            'Paterson Resources Ltd',
            'Pacific Smiles Group Ltd',
            'PS&C Ltd',
            'PTB Group Ltd',
            'Pental Ltd',
            'Platinum Asset Management Ltd',
            'Petratherm Ltd',
            'Prescient Therapeutics Ltd',
            'Pure Alumina Ltd',
            'Pursuit Minerals Ltd',
            'Po Valley Energy Ltd',
            'Powerhouse Ventures Ltd',
            'Pivotal Systems Corporation',
            'Primewest',
            'PWR Holdings Ltd',
            'Powerwrap Ltd',
            'Parkway Minerals NL',
            'Parkway Minerals NL',
            'Pharmaxis Ltd',
            'Polarx Ltd',
            'PYC Therapeutics Ltd',
            'Paygroup Ltd',
            'Betashares Agriculture ETF-Currency Hedged (Synthetic)',
            'Qantas Airways Ltd',
            'Betashares Gold Bullion ETF - Currency Hedged',
            'QBE Insurance Group Ltd',
            'Betashares Commodities Basket ETF-Currency Hedged(Synthetic)',
            'QEM Ltd',
            'Quickfee Ltd',
            'Betashares Australian Financials Sector ETF',
            'Quantify Technology Holdings Ltd',
            'Quantum Graphite Ltd',
            'Vaneck Vectors MSCI World Ex Australia Quality (Hedged) ETF',
            'Quickstep Holdings Ltd',
            'QANTM Intellectual Property Ltd',
            'Betashares Global Quality Leaders ETF',
            'SPDR MSCI World Quality MIX Fund',
            'Betashares Ftse Rafi Australia 200 ETF',
            'Betashares Australian Bank Senior Floating Rate Bond ETF',
            'Quattro Plus Real Estate',
            'Betashares Australian Resources Sector ETF',
            'Qualitas Real Estate Income Fund',
            'Questus Ltd',
            'Q Technology Group Ltd',
            'Quantum Health Group Ltd',
            'Vaneck Vectors MSCI World Ex Australia Quality ETF',
            'QUBE Holdings Ltd',
            'Queste Communications Ltd',
            'Betashares Ftse Rafi U.S. 1000 ETF',
            'QV Equities Ltd',
            'R3D Global Ltd',
            'Race Oncology Ltd',
            'Ragnar Metals Ltd',
            'Range International Ltd',
            'Resapp Health Ltd',
            'Russell Investments Australian Responsible Investment ETF',
            'Restaurant Brands New Zealand Ltd',
            'Redbubble Ltd',
            'RBR Group Ltd',
            'Betashares Global Robotics and Artificial Intelligence ETF',
            'Resource Base Ltd',
            'Russell Investments Australian Select Corporate Bond ETF',
            'Recce Pharmaceuticals Ltd',
            'Readcloud Ltd',
            'Redbank Copper Ltd',
            'Reef Casino Trust',
            'Rightcrowd Ltd',
            'Registry Direct Ltd',
            'Redcape Hotel Group',
            'Redflex Holdings Ltd',
            'Resource Development Group Ltd',
            'Redhill Education Ltd',
            'Red Metal Ltd',
            'Raiden Resources Ltd',
            'Redstone Resources Ltd',
            'Russell Investments High Dividend Australian Shares ETF',
            'Readytech Holdings Ltd',
            'Resa Group Ltd',
            'REA Group Ltd',
            'RED 5 Ltd',
            'RAREX Ltd',
            'Reverse Corp Ltd',
            'Regis Healthcare Ltd',
            'Reece Ltd',
            'Vaneck Vectors Ftse International Property (Hedged) ETF',
            'AMP Capital Global Property Sec Fund',
            'Resource Generation Ltd',
            'Real Estate Investar Group Ltd',
            'Regional Express Holdings Ltd',
            'REY Resources Ltd',
            'Resources & Energy Group Ltd',
            'Regal Investment Fund',
            'Rural Funds Group',
            'Retail Food Group Ltd',
            'Reffind Ltd',
            'Rafaella Resources Ltd',
            'Rectifier Technologies Ltd',
            'Redflow Ltd',
            'Russell Investments Australian Government Bond ETF',
            'Roto-Gro International Ltd',
            'Riversgold Ltd',
            'Regeneus Ltd',
            'Ramsay Health Care Ltd',
            'Red Hill Iron Ltd',
            'Rhipe Ltd',
            'Resonance Health Ltd',
            'RHYTHM Biosciences Ltd',
            'Ridley Corporation Ltd',
            'Riedel Resources Ltd',
            'Rimfire Pacific Mining NL',
            'Betashares Legg Mason Real Income Fund (Managed Fund)',
            'RIO Tinto Ltd',
            'Reckon Ltd',
            'Reedy Lagoon Corporation Ltd',
            'Real Energy Corporation Ltd',
            'Roolife Group Ltd',
            'Renergen Ltd',
            'Resimac Group Ltd',
            'Resmed Inc',
            'RMG Ltd',
            'Resource Mining Corporation Ltd',
            'Resolution Minerals Ltd',
            'Red Emperor Resources NL',
            'Ramelius Resources Ltd',
            'Rma Energy Ltd',
            'Red Mountain Mining Ltd',
            'Rma Global Ltd',
            'Rand Mining Ltd',
            'Renu Energy Ltd',
            'Rhinomed Ltd',
            'Rent.com.Au Ltd',
            'Renascor Resources Ltd',
            'Renegade Exploration Ltd',
            'RNY Property Trust',
            'ETFs Robo Global Robotics and Automation ETF',
            'Red Sky Energy Ltd',
            'Roots Sustainable Agricultural Technologies Ltd',
            'Raptis Group Ltd',
            'RPM Automotive Group Ltd',
            'Regis Resources Ltd',
            'Resolute Mining Ltd',
            'Respiri Ltd',
            'Russell Investments Australian Semi-Government Bond ETF',
            'Retech Technology Co., Ltd',
            'RTG Mining Inc',
            'Rumble Resources Ltd',
            'Rpmglobal Holdings Ltd',
            'Red River Resources Ltd',
            'Revasum Inc',
            'Reliance Worldwide Corporation Ltd',
            'Reward Minerals Ltd',
            'Rewardle Holdings Ltd',
            'ROX Resources Ltd',
            'REX Minerals Ltd',
            'RXP Services Ltd',
            'Ryder Capital Ltd',
            'RAIZ Invest Ltd',
            'S2 Resources Ltd',
            'SOUTH32 Ltd',
            'Star Combo Pharma Ltd',
            'SIV Asset Management Ltd',
            'Sagalio Energy Ltd',
            'Saracen Mineral Holdings Ltd',
            'Sky and Space Global Ltd',
            'Southern Gold Ltd',
            'Pinnacle Ashares Global Dynamic Income Fund (Managed Fund)',
            'Sterling Plantations Ltd',
            'ST Barbara Ltd',
            'Sabre Resources Ltd',
            'Siburan Resources Ltd',
            'Shekel Brainweigh Ltd',
            'Scentre Group',
            'Silver City Minerals Ltd',
            'Schrole Group Ltd',
            'Scorpion Minerals Ltd',
            'Shopping Centres Australasia Property Group',
            'Scout Security Ltd',
            'Stemcell United Ltd',
            'Speedcast International Ltd',
            'Steadfast Group Ltd',
            'Sunland Group Ltd',
            'SDI Ltd',
            'Sundance Resources Ltd',
            'Scidev Ltd',
            'Sienna Cancer Diagnostics Ltd',
            'Sensera Ltd',
            'Spheria Emerging Companies Ltd',
            'Speciality Metals International Ltd',
            'Seek Ltd',
            'Selfwealth SMSF Leaders ETF',
            'Senetas Corporation Ltd',
            'Sequoia Financial Group Ltd',
            'Strategic Energy Resources Ltd',
            'Secos Group Ltd',
            'Stemify Ltd',
            'Schaffer Corporation Ltd',
            'Seafarms Group Ltd',
            'Santa Fe Minerals Ltd',
            'Sandfire Resources Ltd',
            'Sheffield Resources Ltd',
            'SPDR S&P/ASX 50 Fund',
            'Sacgasco Ltd',
            'SG Fleet Group Ltd',
            'Slater & Gordon Ltd',
            'Stealth Global Holdings Ltd',
            'Ricegrowers Ltd',
            'Sims Ltd',
            'Stream Group Ltd',
            'Stockland',
            'ST George Mining Ltd',
            'The Star Entertainment Group Ltd',
            'Stonehorse Energy Ltd',
            'Shree Minerals Ltd',
            'Shine Justice Ltd',
            'Stone Resources Australia Ltd',
            'Sonic Healthcare Ltd',
            'Shriro Holdings Ltd',
            'Sportshero Ltd',
            'Select Harvests Ltd',
            'SIX Sigma Metals Ltd',
            'Sigma Healthcare Ltd',
            'Sihayo Gold Ltd',
            'Smiles Inclusive Ltd',
            'Simonds Group Ltd',
            'Smartgroup Corporation Ltd',
            'Simble Solutions Ltd',
            'Site Group International Ltd',
            'SIV Capital Ltd',
            'Sprintex Ltd',
            'Skycity Entertainment Group Ltd',
            'SKYFII Ltd',
            'Spark Infrastructure Group',
            'Skin Elements Ltd',
            'Serko Ltd',
            'Sky Network Television Ltd',
            'SKY Metals Ltd',
            'SYMBOL Mining Ltd',
            'Superloop Ltd',
            'SPDR S&P/ASX 200 Listed Property Fund',
            'Sealink Travel Group Ltd',
            'Salmat Ltd',
            'Silver Lake Resources Ltd',
            'SILEX Systems Ltd',
            'Sultan Resources Ltd',
            'Synlait Milk Ltd',
            'Strategic Minerals Corporation NL',
            'Soon Mining Ltd',
            'Santana Minerals Ltd',
            'Betashares Aust Small Companies Select Fund (Managed Fund)',
            'Structural Monitoring Systems Plc',
            'Smartpay Holdings Ltd',
            'Stanmore Coal Ltd',
            'Security Matters Ltd',
            'Sandon Capital Investments Ltd',
            'Saunders International Ltd',
            'Supply Network Ltd',
            'Sensen Networks Ltd',
            'Summerset Group Holdings Ltd',
            'Salt Lake Potash Ltd',
            'Washington H Soul Pattinson & Company Ltd',
            'Somnomed Ltd',
            'Synertec Corporation Ltd',
            'Strategic Elements Ltd',
            'Spectur Ltd',
            'Spark New Zealand Ltd',
            'Starpharma Holdings Ltd',
            'Superior Resources Ltd',
            'Splitit Payments Ltd',
            'Spectrum Metals Ltd',
            'SPDR S&P 500 ETF Trust',
            'Smart Parking Ltd',
            'SRG Global Ltd',
            'Saferoads Holdings Ltd',
            'Sipa Resources Ltd',
            'Strike Resources Ltd',
            'Surefire Resources NL',
            'Servcorp Ltd',
            'Story-I Ltd',
            'Stellar Resources Ltd',
            'Shaver Shop Group Ltd',
            'Sietel Ltd',
            'Sietel Ltd',
            'Service Stream Ltd',
            'SPDR S&P/ASX Small Ordinaries Fund',
            'Steamships Trading Company Ltd',
            'Spirit Telecom Ltd',
            'Strandline Resources Ltd',
            'Sinetech Ltd',
            'Straker Translations Ltd',
            'Sunstone Metals Ltd',
            'Saturn Metals Ltd',
            'Santos Ltd',
            'SPDR S&P/ASX 200 Fund',
            'Strike Energy Ltd',
            'Vaneck Vectors Australian Subordinated Debt ETF',
            'Suda Pharmaceuticals Ltd',
            'Southern Hemisphere Mining Ltd',
            'Super Retail Group Ltd',
            'Suncorp Group Ltd',
            'Superior Lake Resources Ltd',
            'Simavita Ltd',
            'Scandivanadium Ltd',
            'Silver Heritage Group Ltd',
            'Silver Mines Ltd',
            'Sovereign Metals Ltd',
            'Sunvest Corporation Ltd',
            'Seven Group Holdings Ltd',
            'Stavely Minerals Ltd',
            'Swift Media Ltd',
            'Selfwealth Ltd',
            'Swick Mining Services Ltd',
            'Seven West Media Ltd',
            'Switzer Dividend Growth Fund (Managed Fund)',
            'Strata-X Energy Ltd',
            'Southern Cross Electrical Engineering Ltd',
            'Southern Cross Media Group Ltd',
            'Southern Cross Exploration N.L.',
            'SENEX Energy Ltd',
            'Sayona Mining Ltd',
            'Sydney Airport',
            'SPDR MSCI Australia Select High Dividend Yield Fund',
            'Syrah Resources Ltd',
            'SYNGAS Limited',
            'Syntonic Ltd',
            'Sezzle Inc',
            '333D Ltd',
            'Tabcorp Holdings Ltd',
            'Tanami Gold NL',
            'TAO Commodities Ltd',
            'TAP Oil Ltd',
            'Taruga Minerals Ltd',
            'Tasman Resources Ltd',
            'Tambla Ltd',
            'Tribune Resources Ltd',
            'Transurban Group',
            'Techniche Ltd',
            'Transmetro Corporation Ltd',
            'Tali Digital Ltd',
            '360 Capital Digital Infrastructure Fund',
            'TBG Diagnostics Ltd',
            '3D Oil Ltd',
            'Thedocyard Ltd',
            'ETFs Morningstar Global Technology ETF',
            'Triangle Energy (Global) Ltd',
            'Thorney Technologies Ltd',
            'Terracom Ltd',
            'Tasfoods Ltd',
            'Thorn Group Ltd',
            'Tribeca Global Natural Resources Ltd',
            'Templeton Global Growth Fund Ltd',
            'Terragen Holdings Ltd',
            'Theta Gold Mines Ltd',
            'Tungsten Mining NL',
            'Trimantium Growthops Ltd',
            '360 Capital Group',
            'Tassal Group Ltd',
            'THC Global Group Ltd',
            'Thred Ltd',
            'Thor Mining Plc',
            'Tian An Australia Ltd',
            'Tietto Minerals Ltd',
            'Tigers Realm Coal Ltd',
            'TNT Mines Ltd',
            'Teaminvest Private Group Ltd',
            'Tikforce Ltd',
            'Traka Resources Ltd',
            'Trek Metals Ltd',
            'Talga Resources Ltd',
            'Talisman Mining Ltd',
            'Telstra Corporation Ltd',
            'Tilt Renewables Ltd',
            'TELIX Pharmaceuticals Ltd',
            'Trigg Mining Ltd',
            'Tamaska Oil and Gas Ltd',
            'Timah Resources Ltd',
            'Tempus Resources Ltd',
            'Technology Metals Australia Ltd',
            'Terrain Minerals Ltd',
            'Thomson Resources Ltd',
            'Technology One Ltd',
            'TNG Ltd',
            'Think Childcare Group',
            'Triple Energy Ltd',
            'Torian Resources Ltd',
            'Tesserent Ltd',
            'Tinybeans Group Ltd',
            'Toro Energy Ltd',
            'Tomizone Ltd',
            'Triton Minerals Ltd',
            'Thorney Opportunities Ltd',
            '360 Capital REIT',
            'Tlou Energy Ltd',
            'TPC Consolidated Ltd',
            'Talon Petroleum Ltd',
            'TPG Telecom Ltd',
            'Tian Poh Resources Ltd',
            'Tempo Australia Ltd',
            'Threat Protect Australia Ltd',
            'Temple & Webster Group Ltd',
            'Turners Automotive Group Ltd',
            'Tanga Resources Ltd',
            'Truscott Mining Corporation Ltd',
            'The Reject Shop Ltd',
            'Todd River Resources Ltd',
            'Troy Resources Ltd',
            'Twenty Seven Co. Ltd',
            'Titanium Sands Ltd',
            'Tesoro Resources Ltd',
            'TTA Holdings Ltd',
            'Total Brain Ltd',
            'Traffic Technologies Ltd',
            'Transcendence Technologies Ltd',
            'Titan Minerals Ltd',
            'Titomic Ltd',
            'TV2U International Ltd',
            'Tamawood Ltd',
            'Treasury Wine Estates Ltd',
            'Tower Ltd',
            'TYMLEZ Group Ltd',
            'Tyro Payments Ltd',
            'Tyranna Resources Ltd',
            'TZ Ltd',
            'Terramin Australia Ltd',
            'Ubs IQ MSCI Australia Ethical ETF',
            'Ubs IQ MSCI Europe Ethical ETF',
            'Universal Biosensors Inc',
            'Ubs IQ MSCI Japan Ethical ETF',
            'Urbanise.com Ltd',
            'Ubs IQ MSCI Asia APEX 50 Ethical ETF',
            'Ubs IQ MSCI Usa Ethical ETF',
            'Ubs IQ MSCI World Ex Australia Ethical ETF',
            'Uscom Ltd',
            'UCW Ltd',
            'Betashares S&P 500 Yield Maximiser Fund',
            'United Malt Group Ltd',
            'United Networks Ltd',
            'Universal Coal Plc',
            'United Overseas Australia Ltd',
            'US Masters Residential Property Fund',
            'Unibail-Rodamco-Westfield',
            'Betashares U.S. Dollar ETF',
            'Ultracharge Limited',
            'Ultima United Ltd',
            'UUV Aquabotix Ltd',
            'Uniti Group Ltd',
            'Vanguard Australian Corp Fixed Interest INDEX ETF',
            'Vanguard Ftse Asia Ex Japan Shares INDEX ETF',
            'Vanguard Australian Fixed Interest INDEX ETF',
            'Virgin Australia Holdings Ltd',
            'Valor Resources Ltd',
            'Vango Mining Ltd',
            'Vanguard Australian Property Securities INDEX ETF',
            'Variscan Mines Ltd',
            'Vanguard Australian Shares INDEX ETF',
            'Vanguard Global Infrastructure INDEX ETF',
            'Vanguard Global Aggregate Bond INDEX (Hedged) ETF',
            'Vectus Biosystems Ltd',
            'Vanguard International Credit Securities INDEX (Hedged) ETF',
            'Vicinity Centres',
            'Vanguard Diversified Balanced INDEX ETF',
            'Vanguard Diversified Conservative INDEX ETF',
            'Vanguard Diversified Growth INDEX ETF',
            'Vanguard Diversified High Growth INDEX ETF',
            'Viva Energy Group Ltd',
            'Vector Resources Ltd',
            'Veem Ltd',
            'Vanguard Ethically Conscious GLB Agg Bond INDEX (Hedged) ETF',
            'Vintage Energy Ltd',
            'Vanguard Ftse Europe Shares ETF',
            'Vanguard Ethically Conscious International Shares INDEX ETF',
            'Vanguard All-World Ex-US Shares INDEX ETF',
            'Vgi Partners Global Investments Ltd',
            'Vgi Partners Asian Investments Ltd',
            'Vanguard MSCI INDEX International Shares (Hedged) ETF',
            'Vanguard Australian Government Bond INDEX ETF',
            'Vanguard Ftse Emerging Markets Shares ETF',
            'VGI Partners Ltd',
            'Vista Group International Ltd',
            'Vanguard Global Multi-Factor Active ETF (Managed Fund)',
            'Vanguard MSCI INDEX International Shares ETF',
            'Volpara Health Technologies Ltd',
            'Vanguard Australian Shares High Yield ETF',
            'Viagold Capital Ltd',
            'Victory Mines Ltd',
            'Vanguard International Fixed Interest INDEX (Hedged) ETF',
            'Victor Group Holdings Ltd',
            'Vietnam Industrial Investments Ltd',
            'VIP Gloves Ltd',
            'Vanguard MSCI International Small Companies INDEX ETF',
            'Vivid Technology Ltd',
            'Viking Mines Ltd',
            'Vanguard MSCI Australian Large Companies INDEX ETF',
            'Vita Life Sciences Ltd',
            'Vault Intelligence Ltd',
            'Venus Metals Corporation Ltd',
            'VDM Group Ltd',
            'Vanguard Global Minimum Volatility Active ETF (Managed Fund)',
            'Vital Metals Ltd',
            'Venture Minerals Ltd',
            'Vmoto Ltd',
            'Valmec Ltd',
            'Vimy Resources Ltd',
            'VONEX Ltd',
            'Vocus Group Ltd',
            'Victory Offices Ltd',
            'Vortiv Ltd',
            'Velocity Property Group Ltd',
            'VPCL Ltd',
            'Volt Power Group Ltd',
            'Vection Technologies Ltd',
            'Vanadium Resources Ltd',
            'Volt Resources Ltd',
            'Village Roadshow Ltd',
            'Veris Ltd',
            'Virtus Health Ltd',
            'VRX Silica Ltd',
            'Vanguard MSCI Australian Small Companies INDEX ETF',
            'Vita Group Ltd',
            'Vitalharvest Freehold Trust',
            'Visioneering Technologies, Inc',
            'Vanguard US Total Market Shares INDEX ETF',
            'Virgin Money Uk Plc',
            'Vulcan Energy Resources Ltd',
            'Viva Leisure Ltd',
            'Vanguard Global Value Equity Active ETF (Managed Fund)',
            'Viva Energy REIT',
            'Venturex Resources Ltd',
            'Vysarn Ltd',
            'Wam Active Ltd',
            'West African Resources Ltd',
            'WAM Capital Ltd',
            'Waterco Ltd',
            'Wam Research Ltd',
            'Westpac Banking Corporation',
            'Whitebark Energy Ltd',
            'Weebit Nano Ltd',
            'WCM Quality Global Growth Fund (Quoted Managed Fund)',
            'White Cliff Minerals Ltd',
            'SPDR S&P Global Dividend Fund',
            'Ishares Edge MSCI World Multifactor ETF',
            'Webjet Ltd',
            'White Energy Company Ltd',
            'Winchester Energy Ltd',
            'SPDR S&P Emerging Markets Fund',
            'Wesfarmers Ltd',
            'Winmar Resources Ltd',
            'Wam Global Ltd',
            'Wagners Holding Company Ltd',
            'Warrego Energy Ltd',
            'Westgold Resources Ltd',
            'Wattle Health Australia Ltd',
            'Whitehaven Coal Ltd',
            'Whitefield Ltd',
            'Whitefield Ltd',
            'Whitehawk Ltd',
            'Westoz Investment Company Ltd',
            'Wameja Ltd',
            'Walkabout Resources Ltd',
            'Wollongong Coal Ltd',
            'Wellard Ltd',
            'Wam Leaders Ltd',
            'Wolf Minerals',
            'Wam Microcap Ltd',
            'Woomera Mining Ltd',
            'Wellness and Beauty Solutions Ltd',
            'Windlab Ltd',
            'Wingara AG Ltd',
            'World.Net Services Ltd',
            'Wide Open Agriculture Ltd',
            'Worley Ltd',
            'Woolworths Group Ltd',
            'Woodside Petroleum Ltd',
            'WPP AUNZ Ltd',
            'WCM Global Growth Ltd',
            'Betashares Managed Risk Global Share Fund (Managed Fund)',
            'White Rock Minerals Ltd',
            'Western Areas Ltd',
            'Weststar Industrial Ltd',
            'Whispir Ltd',
            'Wisetech Global Ltd',
            'WT Financial Group Ltd',
            'Ishares Edge MSCI World Minimum Volatility ETF',
            'Wiseway Group Ltd',
            'West Wits Mining Ltd',
            'SPDR S&P World Ex Australia (Hedged) Fund',
            'SPDR S&P World Ex Australia Fund',
            'Wisr Ltd',
            'Xanadu Mines Ltd',
            'Activex Ardea Real Outcome Bond Fund (Managed Fund)',
            'XCD Energy Ltd',
            'Xref Ltd',
            'XPD Soccer Gear Group Ltd',
            'Xped Ltd',
            'Xplore Wealth Ltd',
            'XRF Scientific Ltd',
            'Xero Ltd',
            'Xstate Resources Ltd',
            'Xantippe Resources Ltd',
            'XTD Ltd',
            'Xtek Ltd',
            'Yancoal Australia Ltd',
            'Betashares Strong U.S. Dollar Fund (Hedge Fund)',
            'Yellow Brick Road Holdings Ltd',
            'Betashares Aus TOP20 Equity Yield MAX Fund (MG FD)',
            'Yojee Ltd',
            'Yowie Group Ltd',
            'YPB Group Ltd',
            'Yandal Resources Ltd',
            'ZIP Co Ltd',
            'Pinnacle Ashares Dynamic Cash Fund (Managed Fund)',
            'Z Energy Ltd',
            'Zenith Energy Ltd',
            'ZETA Resources Ltd',
            'ZEUS Resources Ltd',
            'ZICOM Group Ltd',
            'Zimplats Holdings Ltd',
            'Ziptel Ltd',
            'Zelira Therapeutics Ltd',
            'ZINC of Ireland NL',
            'ZINC of Ireland NL',
            'Zenith Minerals Ltd',
            'ZOONO Group Ltd',
            'ETFs Enhanced Usd Cash ETF',
            'ETFs S&P/ASX 300 High Yield Plus ETF',
            'ZYBER Holdings Ltd',
            'ETFs S&P 500 High Yield Low Volatility ETF'
        ]
        setHintData(hintArray)
    }
  
    useEffect(()=> {
      getData()
    })
  
    return (
      <div className={styles.container}>
        <Hint options={hintData} allowTabFill>
          <input className={styles.inputField}
            value={text}
            onChange={e => setText(e.target.value)} 
          />
        </Hint>
      </div>
    );
  }
  
  export default SearchBar;